# Generated by Django 4.1.2 on 2022-10-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=140)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'datetime'],
            },
        ),
    ]
